### ISSUE TITLE
mlrt_W2x: scale=1 doesn't work

### ISSUE THREAD

**Issue by DonCanjas** [Asd-g/avs-mlrt#1]
When trying to denoise with W2x, while keeping ``scale=1``, it'll give me this error:
![New File000000](https://user-images.githubusercontent.com/80267631/220649482-20b99748-fcfe-4e20-8f92-eda5339d7697.png)

```
ColorBarsHD()
z_ConvertFormat(pixel_type="RGBPS", resample_filter="spline36")
mlrt_W2x(noise=1, scale=1, tiles=4, overlap_w=16, overlap_h=16)
```

Using ``scale=2`` will work, but I'm not interested in upscaling.

**Comment by Asd-g** [comment]
Try the updated version.

**Comment by DonCanjas** [comment]
Seems like everything is fine, thank you.
