### ISSUE TITLE
[mlrt_ort] Error with parameter device=1

### ISSUE THREAD

**Issue by kedaitinh12** [Asd-g/avs-mlrt#10]
I try with parameter device=1 (cause with device=0, the provider=mlt always chooses my iGPU), my dGPU starts with using vram but i meet this error
![image](https://github.com/Asd-g/avs-mlrt/assets/66716952/e346587d-0970-418f-9f7d-aadffc5e7736)

My script:
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\ffms\ffms2.dll")
FFImageSource("C:\Users\ADMIN\Downloads\LCFome7.jpeg")
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ort(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.onnx", builtin=false, fp16=true, provider="dml", device=1)
propSet("_FieldBased",0)
deep_resize(1920,1080,grain=0)
z_ConvertFormat(pixel_type="yuv420p8", colorspace_op="rgb:709:709:f=>709:709:709:l")

when i change to mlrt_ort(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.onnx", builtin=false, fp16=true, provider="dml", device=1, tilesize_w=width/2, tilesize_h=height/2), the script works so I think it relates my dedicated GPU memory not enough but I can launch the script even use shared GPU memory in Vapoursynth version

**Comment by Asd-g** [comment]
Try with the attached DirectML.dll.

[DirectML.zip](https://github.com/Asd-g/avs-mlrt/files/14184723/DirectML.zip)

**Comment by kedaitinh12** [comment]
same error

**Comment by Asd-g** [comment]
Can you share `RealESRGAN_x4plus_anime_6B.onnx` ?

**Comment by kedaitinh12** [comment]
here
[RealESRGAN_x4plus_anime_6B.zip](https://github.com/Asd-g/avs-mlrt/files/14203678/RealESRGAN_x4plus_anime_6B.zip)

**Comment by Asd-g** [comment]
Thanks.

Are you sure that the vs version is running without specifying tilesize and with the same gpu selected?

**Comment by kedaitinh12** [comment]
yes, sample preview work + script + GPU usage in the image below
![image](https://github.com/Asd-g/avs-mlrt/assets/66716952/cf08d396-b178-4473-9512-0336a23bfb99)

**Comment by Asd-g** [comment]
You're using a wrapper. Can you try with `core.ort.Model(....)` ?

**Comment by kedaitinh12** [comment]
I use Hybrid so I know about this app. If I add title size the script will like this
![image](https://github.com/Asd-g/avs-mlrt/assets/66716952/3a19fac0-4c03-4cfd-a8e2-77ce76422fda)

**Comment by Asd-g** [comment]
Please redownload runtime files from [Releases](https://github.com/Asd-g/avs-mlrt/releases) and follow [the updated guide about the runtime files](https://github.com/Asd-g/avs-mlrt/tree/main/mlrt_ort#runtime-files).

**Comment by kedaitinh12** [comment]
I do like you but both Cuda and DML don't work now
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\ffms\ffms2.dll")
FFImageSource("C:\Users\ADMIN\Downloads\LCFome7.jpeg")
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ort(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.onnx", builtin=false, fp16=true, provider="cuda", device=0)
propSet("_FieldBased",0)
deep_resize(1920,1080,grain=0)
z_ConvertFormat(pixel_type="yuv420p8", colorspace_op="rgb:709:709:f=>709:709:709:l")
![image](https://github.com/Asd-g/avs-mlrt/assets/66716952/38781d70-ae27-4c8b-9b6c-4a5bb84452bb)
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\ffms\ffms2.dll")
FFImageSource("C:\Users\ADMIN\Downloads\LCFome7.jpeg")
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ort(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.onnx", builtin=false, fp16=true, provider="dml", device=1)
propSet("_FieldBased",0)
deep_resize(1920,1080,grain=0)
z_ConvertFormat(pixel_type="yuv420p8", colorspace_op="rgb:709:709:f=>709:709:709:l")
![image](https://github.com/Asd-g/avs-mlrt/assets/66716952/1af5e64a-9662-4750-9738-08891b3167ff)
My mlrt_ort_loader.avsi
LoadDLL(".\ort_dll\cublasLt64_12.dll")
LoadDLL(".\ort_dll\cudart64_12.dll")
LoadDLL(".\ort_dll\cublas64_12.dll")
LoadDLL(".\ort_dll\cufft64_11.dll")
LoadDLL(".\ort_dll\cudnn_ops_infer64_8.dll")
LoadDLL(".\ort_dll\cudnn_cnn_infer64_8.dll")
LoadDLL(".\ort_dll\cudnn_adv_infer64_8.dll")
LoadDLL(".\ort_dll\DirectML.dll")
LoadDLL(".\ort_dll\onnxruntime.dll")
LoadPlugin("mlrt_ort.dll")

**Comment by Asd-g** [comment]
Is there error if `tilesize_...` is used?

**Comment by kedaitinh12** [comment]
> Is there error if `tilesize_...` is used?

with runtimes files before, i can work with Cuda ver without tilesize by just putting all files into plugins64+

**Comment by kedaitinh12** [comment]
Yeah, same error with tilesize
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\ffms\ffms2.dll")
FFImageSource("C:\Users\ADMIN\Downloads\LCFome7.jpeg")
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ort(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.onnx", builtin=false, fp16=true, provider="dml", device=1, tilesize_w=width/2, tilesize_h=height/2)
propSet("_FieldBased",0)
deep_resize(1920,1080,grain=0)
z_ConvertFormat(pixel_type="yuv420p8", colorspace_op="rgb:709:709:f=>709:709:709:l")

**Comment by Asd-g** [comment]
Try with edited `mlrt_ort_loader.avsi` to 

```
LoadDLL(".\ort_dll\DirectML.dll")
LoadDLL(".\ort_dll\onnxruntime.dll")
LoadPlugin("mlrt_ort.dll")
```

**Comment by kedaitinh12** [comment]
same error

**Comment by kedaitinh12** [comment]
I tried to delete mlrt_ov_loader.avsi and mlrt_ort_loader.avsi. Put all runtime files to plugins64+ and use [onnxruntime_only_dml.zip](https://github.com/Asd-g/avs-mlrt/files/14239867/onnxruntime_only_dml.zip), DML works with this script now (without tilesize)
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\ffms\ffms2.dll")
FFImageSource("C:\Users\ADMIN\Downloads\LCFome7.jpeg")
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ort(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.onnx", builtin=false, fp16=true, provider="dml", device=1)
propSet("_FieldBased",0)
deep_resize(1920,1080,grain=0)
z_ConvertFormat(pixel_type="yuv420p8", colorspace_op="rgb:709:709:f=>709:709:709:l")

**Comment by kedaitinh12** [comment]
Next, I put the old onnx runtime back, and Cuda works now (deleted mlrt_ov_loader.avsi and mlrt_ort_loader.avsi. Put all runtime files to plugins64+). Openvino works with and without putting all runtime files in the plugins64+ (if without, need mlrt_ort_loader.avsi to load all runtime files)

**Comment by Asd-g** [comment]
If you have Windows shipped `directml.dll` in `C:\Windows\System32\directml.dll` can you rename that file to `C:\Windows\System32\directml_.dll` and try `onnxruntime.dll` from `Release` (not [onnxruntime_only_dml.zip](https://github.com/Asd-g/avs-mlrt/files/14239867/onnxruntime_only_dml.zip))?

Edit: In Windows 11 check also for file `C:\Windows\System32\onnxruntime.dll`. If there is such file renamed to `C:\Windows\System32\onnxruntime.dll` and try `onnxruntime.dll` from `Release` (not [onnxruntime_only_dml.zip](https://github.com/Asd-g/avs-mlrt/files/14239867/onnxruntime_only_dml.zip)).

**Comment by kedaitinh12** [comment]
> If you have Windows shipped `directml.dll` in `C:\Windows\System32\directml.dll` can you rename that file to `C:\Windows\System32\directml_.dll` and try `onnxruntime.dll` from `Release` (not [onnxruntime_only_dml.zip](https://github.com/Asd-g/avs-mlrt/files/14239867/onnxruntime_only_dml.zip))?
> 
> Edit: In Windows 11 check also for file `C:\Windows\System32\onnxruntime.dll`. If there is such file renamed to `C:\Windows\System32\onnxruntime.dll` and try `onnxruntime.dll` from `Release` (not [onnxruntime_only_dml.zip](https://github.com/Asd-g/avs-mlrt/files/14239867/onnxruntime_only_dml.zip)).

after changing those names, the error is still the same as DML if I don't use onnxruntime_only_dml.zip

**Comment by Asd-g** [comment]
Ok, thanks for the feedback.

**Comment by Asd-g** [comment]
Can you test the attached versions too?

[onnxruntime_m.zip](https://github.com/Asd-g/avs-mlrt/files/14290670/onnxruntime_m.zip)
[onnxruntime_n.zip](https://github.com/Asd-g/avs-mlrt/files/14290671/onnxruntime_n.zip)

**Comment by kedaitinh12** [comment]
> Can you test the attached versions too?
> 
> [onnxruntime_m.zip](https://github.com/Asd-g/avs-mlrt/files/14290670/onnxruntime_m.zip) [onnxruntime_n.zip](https://github.com/Asd-g/avs-mlrt/files/14290671/onnxruntime_n.zip)

What's m and n?

**Comment by kedaitinh12** [comment]
Both have the same error but the error call is from mlrt_ov, I don't know why it's mlrt_ov when I don't call this function (download the image to see cause the image has very many of text)
![New File000000_1](https://github.com/Asd-g/avs-mlrt/assets/66716952/3a23200c-da7b-4bce-b64f-c71701494eef)
My script:
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\ffms\ffms2.dll")
FFImageSource("C:\Users\ADMIN\Downloads\LCFome7.jpeg")
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ort(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.onnx", builtin=false, fp16=true, provider="dml", device=1)
propSet("_FieldBased",0)
deep_resize(1920,1080,grain=0)
z_ConvertFormat(pixel_type="yuv420p8", colorspace_op="rgb:709:709:f=>709:709:709:l")

**Comment by Asd-g** [comment]
Filenames are just marks to know which file what  build config has.

Can you test this? Also use the attached DirectML.dll with the attached onnxruntime.dll.


[build.zip](https://github.com/Asd-g/avs-mlrt/files/14291329/build.zip)

**Comment by kedaitinh12** [comment]
> Filenames are just marks to know which file what build config has.
> 
> Can you test this? Also use the attached DirectML.dll with the attached onnxruntime.dll.
> 
> [build.zip](https://github.com/Asd-g/avs-mlrt/files/14291329/build.zip)
same error with those files and my script
![New File000000_1](https://github.com/Asd-g/avs-mlrt/assets/66716952/a6315fea-efea-4e1e-9b96-5f7ed082a976)

**Comment by SangenBR** [comment]
> > Filenames are just marks to know which file what build config has.
> > Can you test this? Also use the attached DirectML.dll with the attached onnxruntime.dll.
> > [build.zip](https://github.com/Asd-g/avs-mlrt/files/14291329/build.zip)
> > same error with those files and my script
> > ![New File000000_1](https://private-user-images.githubusercontent.com/66716952/305029843-a6315fea-efea-4e1e-9b96-5f7ed082a976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDY5MjksIm5iZiI6MTcwODAwNjYyOSwicGF0aCI6Ii82NjcxNjk1Mi8zMDUwMjk4NDMtYTYzMTVmZWEtZWZlYS00ZTFlLTliOTYtNWY3ZWQwODJhOTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE0MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOTIwMjRlM2Y0ZjVkMjk4MzNiZjY1NjYyYzU2ODE0MDc5Y2YyYjU0OGEwZDBmMDkzOWY4ZjdmNDYzMmUwZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5wrHpsKuiTyTna4AJecCyZj0PWBaopVcD-rXMPr_SI)

the same error I have

**Comment by Asd-g** [comment]
Can you test the attached versions?

[build1.zip](https://github.com/Asd-g/avs-mlrt/files/14300214/build1.zip)

**Comment by SangenBR** [comment]
still with the same error

**Comment by Asd-g** [comment]
Can you share short sample with the used script and model so I can reproduce the issue?

**Comment by SangenBR** [comment]
Sure.

```
SetMemoryMax(8192)

##Load source

DGSource("D:\Encodes\The Guts\01\01.dgi")

#Detint

AnimeIVTC(mode=1,ifade=true,nnedi3pel=true,stabilize=true,aapel=4,smooth=-1,tradius=3,ediandnn=3,degrain=3,threads=12)
#AnimeIVTC(mode=2,bbob=4,ifade=true,nnedi3pel=true,stabilize=true,aapel=4,smooth=-1,tradius=3,ediandnn=3,degrain=3,threads=12,cach

ConvertBits(32)
ConvertToPlanarRGB()
mlrt_ort(network_path="C:\Program Files (x86)\AviSynth+\plugins64\models\onnx\1x_Dotzilla_Compact_80k_net_g.onnx",builtin=false,provider="dml")
ConvertBits(8).ConvertToYV12()

#Crop(6,0,-6,0)
#Fixer(2,0,0,0,chroma=true)

blackmanresizeMT(1416,1080,taps=8,threads=12)
```

[1x_Dotzilla_Compact_80k_net_g.zip](https://github.com/Asd-g/avs-mlrt/files/14301339/1x_Dotzilla_Compact_80k_net_g.zip)

https://openmodeldb.info/models/1x-Dotzilla-Compact

**Comment by Asd-g** [comment]
Thanks. What is the resolution of the clip?

**Comment by SangenBR** [comment]
> Thanks. What is the resolution of the clip?

720x480

**Comment by Asd-g** [comment]
Can you test the following script:

```
BlankClip(pixel_type="rgbps") # If still error test with BlankClip(pixel_type="rgbps", width=240, height=120)
mlrt_ort(network_path="C:\Program Files (x86)\AviSynth+\plugins64\models\onnx\1x_Dotzilla_Compact_80k_net_g.onnx",builtin=false,provider="dml")
```

**Comment by SangenBR** [comment]
the tragedy continues my friend
![Captura de tela 2024-02-15 172244](https://github.com/Asd-g/avs-mlrt/assets/42396360/750430c3-a6d7-4268-b298-4da5dba40290)

**Comment by Asd-g** [comment]
Rename `C:\Windows\System32\directml.dll` to `C:\Windows\System32\directml_.dll` and try again.

**Comment by SangenBR** [comment]
now avspmod closes by itself

**Comment by Asd-g** [comment]
Use the attached `mlrt_ort.dll`. Make sure `DirectML.dll` and `onnxruntime.dll` are in same folder.

[mlrt_ort.zip](https://github.com/Asd-g/avs-mlrt/files/14302451/mlrt_ort.zip)

**Comment by SangenBR** [comment]
![Captura de tela 2024-02-15 181746](https://github.com/Asd-g/avs-mlrt/assets/42396360/004a39bb-8148-40a0-ad9c-bb193b4ee89c)

**Comment by Asd-g** [comment]
Rename `C:\Windows\System32\onnxruntime.dll` to `C:\Windows\System32\onnxruntime_.dll` and try again.

**Comment by SangenBR** [comment]
same mistake

**Comment by Asd-g** [comment]
Remove `mlrt_ort_loader.avsi` if you have it.
Remove all `onnxruntime.dll`, `DirectML.dll`, `onnxruntime_xxx.dll` and all cuda runtime files from your plugins folder.
Put the attached `DirectML.dll` and `onnxruntime.dll` next to downloaded `mlrt_ort.dll` test version.

[native.zip](https://github.com/Asd-g/avs-mlrt/files/14302637/native.zip)

**Comment by SangenBR** [comment]
it was fun
![Captura de tela 2024-02-15 185604](https://github.com/Asd-g/avs-mlrt/assets/42396360/05e73c73-1c9b-4ba1-bb8f-472b2c938afd)

**Comment by Asd-g** [comment]
Thanks for the testing. What's the performance? Better than `mlrt_ncnn`?

**Comment by SangenBR** [comment]
yes and a little faster
also uses less vram

**Comment by SangenBR** [comment]
I saw now that you asked in the other closed topic, which windows do I use

I use Windows 11 latest version

**Comment by Asd-g** [comment]
These Windows versions have `onnxruntime.dll` and `DirectML.dll` in `System32`and they can be loaded instead of the correct one.

**Comment by Asd-g** [comment]
@SangenBR, can you test the attached `onnxruntime.dll` and `DirectML.dll`? Just replace the existing ones with the attached version.

[build1.zip](https://github.com/Asd-g/avs-mlrt/files/14300214/build1.zip)

**Comment by SangenBR** [comment]
> @SangenBR, can you test the attached `onnxruntime.dll` and `DirectML.dll`? Just replace the existing ones with the attached version.
> 
> [build1.zip](https://github.com/Asd-g/avs-mlrt/files/14300214/build1.zip)

It doesn't work, the same error as above

**Comment by Asd-g** [comment]
Ok.

**Comment by SangenBR** [comment]
What works for me and this one from the attachment
I would say it is 10 to 20% compared to `mlrt_ncnn`
[plugins64.zip](https://github.com/Asd-g/avs-mlrt/files/14303451/plugins64.zip)

**Comment by Asd-g** [comment]
Thanks.

**Comment by Asd-g** [comment]
You can try the latest release. Make sure you read https://github.com/Asd-g/avs-mlrt/tree/r63/mlrt_ort#runtime-files

**Comment by SangenBR** [comment]
> You can try the latest release. Make sure you read https://github.com/Asd-g/avs-mlrt/tree/r63/mlrt_ort#runtime-files

Great Asd everything is working perfectly both DML and CUDA

DML and CUDA performance are basically the same, maybe if you have an RTX 30 or 40 it could be better since mine is an RTX 20

**Comment by Asd-g** [comment]
You can rename `C:\Windows\System32\onnxruntime_.dll` to the original `C:\Windows\System32\onnxruntime.dll` and `C:\Windows\System32\directml_.dll` to the original `C:\Windows\System32\directml.dll` if you didn't do it already.

[Here](https://github.com/AmusementClub/vs-mlrt/releases/tag/v13.2) there is comparison with NVIDIA GeForce RTX 3090 (ort_cuda vs ort_dml).

**Comment by Asd-g** [comment]
@kedaitinh12, do you still have the issue from the first comment?

**Comment by kedaitinh12** [comment]
All 3 filters mlrt_ort Cuda, mlrt_ort DML, mlrt_ov work very well now. But i need to add the info, your new mlrt_ov libraries doesn't have tbb.dll anymore but in your info here still have this file, and in my test, mlrt_ov doesn't need this file still work
https://github.com/Asd-g/avs-mlrt/blob/main/mlrt_ov/README.md

**Comment by Asd-g** [comment]
Please download again `openvino_dll.7z`. Added the new `tbb12.dll` file. The README is changed too.

**Comment by kedaitinh12** [comment]
> Please download again `openvino_dll.7z`. Added the new `tbb12.dll` file. The README is changed too.

ok, thanks
