### ISSUE TITLE
I don't know what 'height_' means.

### ISSUE THREAD

**Issue by tormento** [Asd-g/avs-mlrt#13]
```
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
Import("D:\Eseguibili\Media\StaxRip\Apps\Plugins\AVS\DehaloAlpha\Dehalo_alpha.avsi")
Import("D:\Eseguibili\Media\StaxRip\Apps\Plugins\AVS\Dither\mt_xxpand_multi.avsi")
Import("D:\Eseguibili\Media\StaxRip\Apps\Plugins\AVS\FineDehalo\FineDehalo.avsi")
DGSource("M:\In\Monster ~R2J\1-01-B5.dgi",ct=4,cb=0,cl=4,cr=4)
DGTelecide(mode=1, pthresh=3.5)
DGDecimate()
z_convertformat(pixel_type="RGBPS", use_props=0)
mlrt_W2x(backend="ort", model=1, noise=-1, scale=2)
```

gives me the error:

```
I don't know what 'height_' means.
(D:/Programmi/Media/AviSynth+/plugins64+/mlrt_ort-1.1.5-AsdG.avsi, line 203)
(D:/Programmi/Media/AviSynth+/plugins64+/mlrt_ort-1.1.5-AsdG.avsi, line 206)
(M:\In\Monster ~R2J\mlrt_waifu.avs, line 13)
```
I am using your last mlrt with mlrt_W2x.avsi 1.1.6.

**Comment by Asd-g** [comment]
Try the new version `1.1.7`.

**Comment by tormento** [comment]
Tested and working, thank you.

What models do you suggest to upscale anime with mlrt_ort (CUDA)?

I mean: waifu2x was my first try, as I already knew that kind of upscale but I am sure that there are better ones.

**Comment by Asd-g** [comment]
> What models do you suggest to upscale anime with mlrt_ort (CUDA)?

I cannot help with this. Probably places like doom9 forums are better for such questions.

**Comment by lextra2** [comment]
> What models do you suggest to upscale anime with mlrt_ort (CUDA)?
> 

@tormento 

Give [2x_Ani4Kv2_G6i2_Compact_107500_fp32](https://github.com/Sirosky/Upscale-Hub/releases/tag/Ani4K-v2) and [2x_AniSD_AC_G6i2a_Compact_72500_fp32](https://github.com/Sirosky/Upscale-Hub/releases/tag/AniSD-RealPLKSR) a try
