### ISSUE TITLE
Question about hardware usage mlrt.

### ISSUE THREAD

**Issue by Kuronoe-Ookami** [Asd-g/avs-mlrt#2]
Hi, 
I'm using mlrt with the model: "waifu2x cunet noise1_scale2.0x_model.onnx" that I found in [doom9](http://forum.doom9.net/showthread.php?t=184768) about mlrt, but hardware usage is low. Getting an average of 2.5fps. I tried to prefetch(16 ~ 24) in the .avs, but I get an error.
Without setting prefetch it works fine, but slow.

- llocateMemory failed -2
vkAllocateMemory failed -2
vkAllocateMemory failed -2
vkAllocateMemory failed -2vkAllocateMemory failed -2
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkAllocateMemory failed -2
avs [error]: mlrt_ncnn: inference failed occurred while reading frame 0

[usage](https://i.imgur.com/6XHa1qe.png)

Is there any way to increase hardware usage and get some fps? Nothing too impressive.

Thank you for your hard work in keeping the avisynth community alive.

**Comment by Asd-g** [comment]
Hi,
Can you  download [GPU-Z](https://www.techpowerup.com/gpuz/), open it, go to the  "Sensors" tab and then run the script with avsmeter64/ffmpeg/avsr64/AvsPmod-analysis pass (without prefetch)? What's the "GPU load" in GPU-Z?

**Comment by Kuronoe-Ookami** [comment]
Hello,
Thanks for the answer.
Apparently the usage is higher than it shows in the windows manager. 
I'll have to test other usage options.

[imgur](https://i.imgur.com/mlKED0N.png)

If there are any settings I can do, let me know.

Anyway, thanks for the help. :)

**Comment by Asd-g** [comment]
You can try with `prefetch(2)`.

What's your exact script?

**Comment by Kuronoe-Ookami** [comment]
Hi,
Nothing very impressive, I found the post on doom9 by chance and decided to test it.
[pastebin-avs](https://pastebin.com/raw/dcn8cj2r)

I didn't think of testing the prefetch with smaller values, I had a similar problem with KNLMeansCL, which only accepts 16.
As soon as possible I will test with 2.

The many bit-depth and YV/RGB conversions can affect it too, from what I've noticed. There are many filters that only work with specific things, the models always use RGB 32-bits.

Thanks for the answers.

**Comment by Asd-g** [comment]
Btw there is [mlrt_W2x](https://github.com/Asd-g/avs-mlrt/blob/main/mlrt.avsi#L9) wrapper for the built in models.
`mlrt_ncnn(network_path="C:\path\plugins64+\models\waifu2x\cunet\noise1_scale2.0x_model.onnx", builtin=false)` is the same as `mlrt_W2x(noise=1, backend=["ncnn",  "fp16=false"])`.
There is also [this note](https://github.com/Asd-g/avs-mlrt/blob/main/mlrt.avsi#L376-L378). So you can try `mlrt_ncnn(network_path="C:\path\plugins64+\models\waifu2x\cunet\noise1_scale2.0x_model.onnx", builtin=false, fp16=true, num_streams=2/3/4)` or `mlrt_W2x(noise=1, backend=["ncnn",  "num_streams=2/3/4"])`.

**Comment by Kuronoe-Ookami** [comment]
Hi,
I was in doubt if the models would be the same. `mlrt_W2x(noise=1, backend=["ncnn",  "num_streams=2/3/4"])`, that's why I set it manually, in addition to testing others for rainbow/dot, but the result is the same.

I did some more tests, but I think that's right, around 2.5fps.
[imgur](https://i.imgur.com/yidQ7sD.png)

I tested it as you explained, maybe it's a matter of the model itself. 
I tested others that I found in doom9 and some go up a little. Unfortunately this is what I liked the most about the result, I'll have to settle for the fps 😆 
It doesn't bother me, I just wanted to clear up this doubt that you helped me with.

Thank you so much for taking the time and explaining it to me. 💯

**Comment by Asd-g** [comment]
The spikes of the GPU load on the screenshot suggests that for better tuning of your script, you have to put prefetch after every CPU filter in the script and tune the every prefetch number.

If you run a script with mlrt_XXX only you would see not such spikes.
