### ISSUE TITLE
Update mlrt.avsi wrapper to fix models' output

### ISSUE THREAD

**Issue by DonCanjas** [Asd-g/avs-mlrt#4]
The current process with mlrt_w2x() will introduce a tint. I also am aware that when using, at least, cunet model will damage borders in a extension of 4px.

Here's an example of a w2x wrapper that fixes all its problems for, at least, cunet model: https://github.com/Irrational-Encoding-Wizardry/vs-scale/blob/master/vsscale/scale.py#L289-L338 

So basically the process is:
- 1st - limit RGBPS input with ``Expr("x 0 1 clip")``
- 2nd - pad borders by mirroring, keeping resolution at mod4. ex: z_PointResize(Width(last)+8, Height(last)+8, src_top=-4, src_left=-4, src_width=Width(last)+8, src_height=Height(last)+8)
- 3rd - upscale with mlrt_w2x()
- 4th - Crop padding
- 5th - limit RGBPS output with ``Expr("x 0 1 clip")`` or, if *after* extracting luma from a packed RGB clip, ``Expr(w2x, "x 0.5 255 / +")``.

By the way, I'm not noticing any tinting when converting a yuv clip to rgbps, but am noticing a luminosity change when extracting luma and packing it in RGB. So I'm assuming you have the luminosity problem fixed. Also not sure if you have the padding already.

```py
ColorBarsHD()
ExtractY()
z_PointResize(width(last)*2, Height(last)*2)
```
<img src=https://user-images.githubusercontent.com/80267631/228984800-6ecdc1a7-32fd-4cd7-b12b-7e6d1a87e519.png width="400" />

```py
ColorBarsHD()
ExtractY().ConvertBits(32)

MergeRGB(last, last, last)

mlrt_W2x(noise=-1, scale=2, tiles=4, overlap_w=16)

ExtractR()
```
<img src=https://user-images.githubusercontent.com/80267631/228984789-499dca74-4b44-4839-a9fb-b1f315efcc84.png width="400" />

```py
ColorBarsHD()
ExtractY().ConvertBits(32)

MergeRGB(last, last, last)
Expr(last, "x 0 1 clip")

mlrt_W2x(noise=-1, scale=2, tiles=4, overlap_w=16)

ExtractR()
Expr(last, "x 0.5 255 / +")
```
<img src=https://user-images.githubusercontent.com/80267631/228984814-f9107190-edb9-469d-8eff-6dae6b615ce4.png width="400" />

Limiting the RGBPS input would also benefit when using DPIR.

```py
LSMASHVideoSource("test.mp4")
```
<img src=https://user-images.githubusercontent.com/80267631/228977122-f4cf386e-71a3-4a74-bea7-3bfb7c97d4e9.png width="400" />

```py
LSMASHVideoSource("test.mp4")

z_ConvertFormat(pixel_type="RGBPS", colorspace_op="470bg:601:170m:l=>RGB:601:170m:f")

mlrt_DPIR(strength=90, model=3, tiles=6, overlap_w=32)
```
<img src=https://user-images.githubusercontent.com/80267631/228977138-7d79c08c-5f0b-4c41-8b75-150537a1f828.png width="400" />

```py
LSMASHVideoSource("test.mp4")

z_ConvertFormat(pixel_type="RGBPS", colorspace_op="470bg:601:170m:l=>RGB:601:170m:f")

Expr("x 0 1 clip")

mlrt_DPIR(strength=90, model=3, tiles=6, overlap_w=32)
```
<img src=https://user-images.githubusercontent.com/80267631/228977145-0a6af5f9-cff9-4ef0-8bfd-43aff4435aa0.png width="400" />

**Comment by Asd-g** [comment]
You can try the updated version - added mlrt_W2x padding and input clamping.

`Expr("x 0.5 255 / +")` is not perfect either.
```
ColorBarsHD()
ExtractY()
z_ConvertFormat(pixel_type="rgbps")
Expr(last, "x 0 1 clip")

mlrt_W2x(noise=-1, scale=2, tiles=4, overlap_w=16)

Expr(last, "x 0.5 255 / +")
```

The output of above script is a bit reddish compared to the following
```
ColorBarsHD()
ExtractY()
z_ConvertFormat(pixel_type="rgbps")
z_PointResize(width(last)*2, Height(last)*2)
```

I agree with [this comment](https://github.com/AmusementClub/vs-mlrt/issues/2#issuecomment-1093756973). Such operation should be part of the post processing/subjective preferences.

Btw...
```
ColorBarsHD()
ExtractY().ConvertBits(32)

MergeRGB(last, last, last)
```
CombinePlanes is faster than MergeRGB here:
```
ColorBarsHD()
ExtractY().ConvertBits(32)

#MergeRGB(last, last, last)
CombinePlanes(last, planes="rgb", source_planes="yyy", pixel_type="rgbps")
```
Or you can just use the fastest method:
```
ColorBarsHD()
ExtractY()
z_ConvertFormat(pixel_type="rgbps")
```

**Comment by DonCanjas** [comment]
I'm not sure if it's really necessary to use both addborders and fillborders when a simple mirror of the edges with z_PointResize works. And the script should make sure the res is kept at mod4 after padding, so adding 4px borders might be too simplistic in cases where the padded resolution isn't mod4.

Also, ``Expr("x 0.5 255 / +")`` is for Y/YUV while ``Expr(last, "x 0 1 clip")`` is for RGB. Maybe I didn't explain myself properly. Another problem would be if converting to 32 bit before converting to rgb, the limiter will clamp the image unnecessarily making it look faded. That could cause a problem when rescaling video or taking a Y32 input.

Thanks for the tip with CombinePlanes, didn't think of that. Tho seems like to me it's a bit faster to use CombinePlanes then converting with avsresize, while using a bit more RAM. So maybe its speed might depend on how much ram is available.

**Comment by Asd-g** [comment]
> I'm not sure if it's really necessary to use both addborders and fillborders when a simple mirror of the edges with z_PointResize works. And the script should make sure the res is kept at mod4 after padding, so adding 4px borders might be too simplistic in cases where the padded resolution isn't mod4.

AddBorders+FillBorders is faster than z_PointResize with identical output.
If the input resolution is mod4, AddBorders(4,4,4,4) keeps mod4 too. If the input isn't mod4, the resolution after AddBorders(4,4,4,4) is again non-mod4.
The script already checks if the resolution after padding is mod4 - https://github.com/Asd-g/avs-mlrt/blob/main/mlrt.avsi#L158

> Also, Expr("x 0.5 255 / +") is for Y/YUV while Expr(last, "x 0 1 clip") is for RGB. Maybe I didn't explain myself properly. Another problem would be if converting to 32 bit before converting to rgb, the limiter will clamp the image unnecessarily making it look faded. That could cause a problem when rescaling video or taking a Y32 input.

I'm sorry but I cannot understand what you're saying. Can you show some examples to explain what you mean?

**Comment by DonCanjas** [comment]
> The script already checks if the resolution after padding is mod4

Alright, that's good.

> I'm sorry but I cannot understand what you're saying. Can you show some examples to explain what you mean?

Sorry, I was typing that late and got confused myself. ``Expr("x 0.5 255 / +")`` is supposed to correct tint/luminosity, but as I said in my first comment, I didn't really notice a tint. You're right, I can see a redish tint after running ``Expr("x 0.5 255 / +")``.

What I was trying to say is that using ``ConvertBits(32).z_ConvertFormat(pixel_type="RGBPS", ... )`` will look faded. But I noticed that by using ``ConvertBits(32, fulls=false, fulld=true).z_ConvertFormat(pixel_type="RGBPS", ... )``  it won't look faded, so seems like everything is alright.

Seems to me that everything is alrigth

**Comment by Asd-g** [comment]
There is indeed minor tint introduced but as I wrote `Expr("x 0.5 255 / +")` isn't perfect solution. Currently everyone can use whatever he prefers (add `Expr("x 0.5 255 / +")` or not).

> What I was trying to say is that using ConvertBits(32).z_ConvertFormat(pixel_type="RGBPS", ... ) will look faded.

Ah, such type of faded. As you figured out always use `ConvertBits(32, fulls=false, fulld=true)` for converting Y/YUV to 32-bit.
