### ISSUE TITLE
fp16 onnx model support

### ISSUE THREAD

**Issue by the-database** [Asd-g/avs-mlrt#5]
Hello, are fp16 onnx models supported? When trying to use them I am seeing an access violation: 

![image](https://github.com/Asd-g/avs-mlrt/assets/25811902/8d5293f2-d433-444a-a3d4-a82a82ebe742)

If I use the fp32 onnx for the same model I am able to run it with no issues. I am using chainner to convert pth models to fp16 and fp32 onnx models.
![chainner-convert](https://github.com/Asd-g/avs-mlrt/assets/25811902/b5e25a6a-3733-4c84-afce-4d5067e9d874)

Here are some models that reproduce the issue: https://github.com/the-database/mpv-upscale-2x_animejanai/releases/download/2.0.0/2x_AnimeJaNai_V2_ModelsOnly.zip

**Comment by Asd-g** [comment]
Yes, they are supported. Using mlrt.avsi for the builtin models fp16 is true by default - https://github.com/Asd-g/avs-mlrt/blob/main/mlrt.avsi#L441.

I will take a look at the issue these days.

**Comment by Asd-g** [comment]
The attached models fails with `fp16=false` too.

Anyway [ncnn lib](https://github.com/Tencent/ncnn) crashes because of division by zero. (https://github.com/Tencent/ncnn/issues/3180 ?)

Using `mlrt_ov` is ok.
