### ISSUE TITLE
Clip must have video

### ISSUE THREAD

**Issue by kedaitinh12** [Asd-g/avs-mlrt#8]
I got that error when I tried to use avs-mlrt with dpir models

Script:
LoadPlugin("C:\Megui\MeGUI-2944-64\tools\lsmash\LSMASHSource.dll")
LWLibavVideoSource("C:\Users\ADMIN\Downloads\aa.mkv")
z_ConvertFormat(pixel_type="RGBPS", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ncnn(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/dpir/drunet_deblocking_color.onnx", builtin=false, fp16=true, tilesize_w=width/4, tilesize_h=height/4, overlap_w=8, overlap_h=8)
z_ConvertFormat(pixel_type="YUV420P8", colorspace_op="rgb:709:709:f=>709:709:709:l")

Sample: https://forum.doom9.org/showthread.php?p=1993627#post1993627

Models: https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/tag/models
![image](https://github.com/Asd-g/avs-mlrt/assets/66716952/450f3b1e-ed30-4a95-b789-638962891190)

**Comment by Asd-g** [comment]
Both `tilesize_w` and `tilesize_h` must be divisible by 8 for this model.

If you use `mlrt_DPIR(model=3)` you will get error about the tilesize.

**Comment by kedaitinh12** [comment]
> mlrt_DPIR(model=3)

mlrt_DPIR(model=3) is working but the result doesn't look like here:
https://imgsli.com/MjE5Mzcw

My result:
![New File001336_2](https://github.com/Asd-g/avs-mlrt/assets/66716952/bdde68a7-3169-4f68-84d1-99aa710bea31)

Script:
LoadPlugin("C:\Megui\MeGUI-2944-64\tools\lsmash\LSMASHSource.dll")
LWLibavVideoSource("C:\Users\ADMIN\Downloads\aa.mkv")
z_ConvertFormat(pixel_type="RGBPS", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_DPIR(model=3)
z_ConvertFormat(pixel_type="YUV420P8", colorspace_op="rgb:709:709:f=>709:709:709:l")
converttoyuv444()
MSRCP

**Comment by Asd-g** [comment]
What's the script for the first image?

**Comment by kedaitinh12** [comment]
He only use with default settings
https://forum.doom9.org/showthread.php?p=1993694#post1993694

**Comment by kedaitinh12** [comment]
He just add script in link above but i can't make script working with strength=50

**Comment by Asd-g** [comment]
I have no issues with `strength=50`. Try with `tiles`/`tilesize`.

**Comment by kedaitinh12** [comment]
> I have no issues with `strength=50`. Try with `tiles`/`tilesize`.

What value `tiles`/`tilesize` you set??

**Comment by kedaitinh12** [comment]
I tried with this script but result same with mlrt_DPIR(model=3)
LWLibavVideoSource("C:\Users\ADMIN\Downloads\aa.mkv")
z_ConvertFormat(pixel_type="RGBPS", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_DPIR(model=3, strength=50, tiles=8, tilesize=8)
z_ConvertFormat(pixel_type="YUV420P8", colorspace_op="rgb:709:709:f=>709:709:709:l")
converttoyuv444()
MSRCP

btw, can you add parameter device_id to mlrt,avsi all functions?? My machine always chooses AMD onboard card over NVIDIA discrete graphics cards

**Comment by Asd-g** [comment]
I didn't set `tiles`/`tilesize`. This is what I tried:

```
FFVideoSource("aa.mkv")
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:f=>rgb:709:709:f")
mlrt_DPIR(model=3, strength=50)
z_ConvertFormat(pixel_type="rgbp16")
MSRCP(sigma=[25,80,250], fulls=False, fulld=False)
z_ConvertFormat(pixel_type="yuv420p10", colorspace_op="rgb:709:709:l=>709:709:709:l")
```

You can try `mlrt_DPIR(model=3, strength=50, tiles=2)`.

To choose GPU: `mlrt_DPIR(model=3, strength=50, tiles=2, backend=["ncnn", "device_id=X"])` where x is the number of the GPU. You can use `mlrt_DPIR(model=3, strength=50, tiles=2, backend=["ncnn", "list_gpu=true"])` to see the available GPUs.

**Comment by kedaitinh12** [comment]
ok, it work and result look ok with tiles=2, thanks
