### ISSUE TITLE
Crash when use op (opset) models

### ISSUE THREAD

**Issue by kedaitinh12** [Asd-g/avs-mlrt#9]
I always crash app when tried op (opset) models from here:
https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/tag/models

Example:
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\lsmash\LSMASHSource.dll")
LWLibavVideoSource("C:\Users\ADMIN\Downloads\_new.mkv")
a=last
z_ConvertFormat(pixel_type="rgbps", colorspace_op="709:709:709:l=>rgb:709:709:f")
mlrt_ncnn(network_path="C:/Program Files (x86)/AviSynth+/plugins64+/models/Compact/2x_AnimeJaNai_V2_Compact_36k_op18_fp16_clamp.onnx", builtin=false, fp16=true) # Upscales
propSet("_FieldBased",0)
deep_resize(1280,720,edge="SSIM2") 
z_ConvertFormat(pixel_type="yuv420p8", colorspace_op="rgb:709:709:f=>709:709:709:l")

**Comment by Asd-g** [comment]
`2x_AnimeJaNai_V2_Compact_36k_op18_fp16_clamp.onnx` is using `shape` operator. Read [this comment](https://github.com/Asd-g/avs-mlrt/issues/7#issuecomment-1765603255).

`mlrt_ov` is ok.

**Comment by kedaitinh12** [comment]
I got "error unhandled C++ excption!". My AMD CPU don't support mlrt_ov

**Comment by Asd-g** [comment]
Did you try to disable the internal mt for mlrt_ov with `config="CPU_THROUGHPUT_STREAMS=0 CPU_THREADS_NUM=1 CPU_BIND_THREAD=NO"`? You can try also `mlrt_DPIR(backend="ov")`.

**Comment by kedaitinh12** [comment]
Sr, i'm lack openvino runtime, it's work now
